# -----------------------------
# Site Info
# -----------------------------
repository: Geongyu/Geongyu.github.io
version: 2

name: "Geongyu Lee"
title: "AI Researcher | Computational Pathology Â· Multi-Omics Modeling"
email: "gglee@omixai.com"
phone: "+82 10 8408 2255"
website: "https://geongyu.github.io"

darkmode: true

# -----------------------------
# Social
# -----------------------------
github_username: Geongyu
linkedin_username: geongyu-lee
googlescholar_username: 43BuluYAAAAJ

additional_links:
  - title: Google Scholar
    icon: fas fa-graduation-cap
    url: "https://scholar.google.com/citations?user=43BuluYAAAAJ"
  - title: LinkedIn
    icon: fab fa-linkedin
    url: "https://www.linkedin.com/in/geongyu-lee/"

# -----------------------------
# Theme + Build
# -----------------------------
#remote_theme: "sproogen/modern-resume-theme"

plugins:
#  - jekyll-remote-theme
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/"
  - "docker-compose.yml"
